#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'system',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/system',
   :ref => 'master'

cookbook 'rightscale',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/rightscale',
   :ref => 'master'

cookbook 'resolver',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/resolver',
   :ref => 'master'

cookbook 'ruby',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/ruby',
   :ref => 'master'

cookbook 'rubygems',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/rubygems',
   :ref => 'master'

cookbook 'cron',
   :git => 'https://github.com/opscode-cookbooks/cron',
   :ref => 'master'

cookbook 'ntp',
   :git => 'https://github.com/opscode-cookbooks/ntp',
   :ref => 'master'
   
cookbook 'sudo',
   :git => 'https://github.com/opscode-cookbooks/sudo',
   :ref => 'master'

cookbook 'postfix',
   :git => 'https://github.com/opscode-cookbooks/postfix',
   :ref => 'master'

cookbook 'python',
   :git => 'https://github.com/opscode-cookbooks/python',
   :ref => 'master'
