Vagrant::Config.run do |config|

  # name of vagrant box
  config.vm.box = "linux_server"

  # bootstrap provisioning
  config.vm.provision :shell, :inline => 'sed -i "s/#prepend domain-name-servers 127.0.0.1/prepend domain-name-servers 8.8.8.8/g" /etc/dhcp/dhclient.conf && service networking start; gem list | grep chef || gem install chef --no-rdoc --no-ri; apt-get -y update'		# comment out to speed up reloads

  # chef-solo provisioning
  config.vm.provision :chef_solo do |chef|
    #chef.log_level = :debug
    chef.json.merge!(JSON.parse(File.read(File.join(Dir.pwd, '..', 'examples', 'chef-solo', 'node.json'))))
    chef.cookbooks_path = File.join(Dir.pwd, '..', 'cookbooks')
    chef.run_list = [ "recipe[collectd::collectd_web]" ]

  end
end