Vagrant::Config.run do |config|
  config.vm.box = "linux_server"
  config.vm.provision :shell, :inline => 'sed -i "s/#prepend domain-name-servers 127.0.0.1/prepend domain-name-servers 8.8.8.8/g" /etc/dhcp/dhclient.conf && service networking start; gem list | grep chef || gem install chef --no-rdoc --no-ri; apt-get -y update'
  config.vm.provision :chef_solo do |chef|
    #chef.log_level = :debug
    chef.json.merge!(JSON.parse(File.read(File.join(Dir.pwd, '..', 'examples', 'chef-solo', 'node.json'))))
    chef.cookbooks_path = File.join(Dir.pwd, '..', 'cookbooks')
    chef.run_list = [ "recipe[rs_utils]", "recipe[resolver]", "recipe[cron]", "recipe[sudo]", "recipe[ntp]", "recipe[postfix]", "recipe[python]", "recipe[ruby]", "recipe[rubygems]" ]
  end
end